<?php 

	$this->headTitle('Ajouter un élément de workflow');
	$this->headScript()->appendFile($this->baseUrl().'/scripts/jquery/jquery-1.3.2.min.js'); 
	$this->headScript()->appendFile($this->baseUrl().'/scripts/jquery/highlightFade.js');
?>
<script type='text/javascript'>
<?php echo $this->script; ?>
</script>
<h1>Ajouter un élément de workflow</h1>
<?php
	echo $this->form;
?>
<?php if(isset($this->showAddCondition)) {?>
<p>
<a href="#" onClick="addFormField(monTableauJS, 'process_add_step3A_form'); return false;">Add a condition</a>
</p>
<?php }?>