<?php

/**
 * Layout de la partie rapport
 */
echo '<?xml version="1.0" encoding="UTF-8" ?>';
echo $this->doctype() 
?>

<html>

	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<?php 
		echo $this->headTitle();
	    echo $this->headScript();
	    echo $this->headLink();
	    ?>
	</head>
	
	<body>
		<!-- afficher le contenu de la variable $content à l'aide du helper layout() -->
		<?php echo $this->layout()->content ?>
	</body>

</html>
